# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\rsearchPackage\"\'\n\x12SearchMovieRequest\x12\x11\n\tmovieName\x18\x01 \x01(\t\";\n\x08\x42\x36\x34Image\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"@\n\x05Movie\x12\r\n\x05title\x18\x01 \x01(\t\x12(\n\x07\x63\x61rdImg\x18\x02 \x01(\x0b\x32\x17.searchPackage.B64Image\"I\n\x13SearchMovieResponse\x12\r\n\x05\x65xist\x18\x01 \x01(\x08\x12#\n\x05movie\x18\x02 \x03(\x0b\x32\x14.searchPackage.Movie2`\n\rSearchService\x12O\n\x06Search\x12!.searchPackage.SearchMovieRequest\x1a\".searchPackage.SearchMovieResponseb\x06proto3')



_SEARCHMOVIEREQUEST = DESCRIPTOR.message_types_by_name['SearchMovieRequest']
_B64IMAGE = DESCRIPTOR.message_types_by_name['B64Image']
_MOVIE = DESCRIPTOR.message_types_by_name['Movie']
_SEARCHMOVIERESPONSE = DESCRIPTOR.message_types_by_name['SearchMovieResponse']
SearchMovieRequest = _reflection.GeneratedProtocolMessageType('SearchMovieRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHMOVIEREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:searchPackage.SearchMovieRequest)
  })
_sym_db.RegisterMessage(SearchMovieRequest)

B64Image = _reflection.GeneratedProtocolMessageType('B64Image', (_message.Message,), {
  'DESCRIPTOR' : _B64IMAGE,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:searchPackage.B64Image)
  })
_sym_db.RegisterMessage(B64Image)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), {
  'DESCRIPTOR' : _MOVIE,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:searchPackage.Movie)
  })
_sym_db.RegisterMessage(Movie)

SearchMovieResponse = _reflection.GeneratedProtocolMessageType('SearchMovieResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHMOVIERESPONSE,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:searchPackage.SearchMovieResponse)
  })
_sym_db.RegisterMessage(SearchMovieResponse)

_SEARCHSERVICE = DESCRIPTOR.services_by_name['SearchService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHMOVIEREQUEST._serialized_start=31
  _SEARCHMOVIEREQUEST._serialized_end=70
  _B64IMAGE._serialized_start=72
  _B64IMAGE._serialized_end=131
  _MOVIE._serialized_start=133
  _MOVIE._serialized_end=197
  _SEARCHMOVIERESPONSE._serialized_start=199
  _SEARCHMOVIERESPONSE._serialized_end=272
  _SEARCHSERVICE._serialized_start=274
  _SEARCHSERVICE._serialized_end=370
# @@protoc_insertion_point(module_scope)
