# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignup.proto\x12\rsignupPackage\"8\n\rSignupRequest\x12\'\n\x04\x66orm\x18\x01 \x01(\x0b\x32\x19.signupPackage.SignupForm\"2\n\x0eSignupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"X\n\x0bReservation\x12\r\n\x05movie\x18\x01 \x01(\t\x12\x0f\n\x07theater\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\"O\n\nSignupForm\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tpassword1\x18\x03 \x01(\t\x12\x11\n\tpassword2\x18\x04 \x01(\t2V\n\rSignupService\x12\x45\n\x06Signup\x12\x1c.signupPackage.SignupRequest\x1a\x1d.signupPackage.SignupResponseb\x06proto3')



_SIGNUPREQUEST = DESCRIPTOR.message_types_by_name['SignupRequest']
_SIGNUPRESPONSE = DESCRIPTOR.message_types_by_name['SignupResponse']
_RESERVATION = DESCRIPTOR.message_types_by_name['Reservation']
_SIGNUPFORM = DESCRIPTOR.message_types_by_name['SignupForm']
SignupRequest = _reflection.GeneratedProtocolMessageType('SignupRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPREQUEST,
  '__module__' : 'signup_pb2'
  # @@protoc_insertion_point(class_scope:signupPackage.SignupRequest)
  })
_sym_db.RegisterMessage(SignupRequest)

SignupResponse = _reflection.GeneratedProtocolMessageType('SignupResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPRESPONSE,
  '__module__' : 'signup_pb2'
  # @@protoc_insertion_point(class_scope:signupPackage.SignupResponse)
  })
_sym_db.RegisterMessage(SignupResponse)

Reservation = _reflection.GeneratedProtocolMessageType('Reservation', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATION,
  '__module__' : 'signup_pb2'
  # @@protoc_insertion_point(class_scope:signupPackage.Reservation)
  })
_sym_db.RegisterMessage(Reservation)

SignupForm = _reflection.GeneratedProtocolMessageType('SignupForm', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPFORM,
  '__module__' : 'signup_pb2'
  # @@protoc_insertion_point(class_scope:signupPackage.SignupForm)
  })
_sym_db.RegisterMessage(SignupForm)

_SIGNUPSERVICE = DESCRIPTOR.services_by_name['SignupService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNUPREQUEST._serialized_start=31
  _SIGNUPREQUEST._serialized_end=87
  _SIGNUPRESPONSE._serialized_start=89
  _SIGNUPRESPONSE._serialized_end=139
  _RESERVATION._serialized_start=141
  _RESERVATION._serialized_end=229
  _SIGNUPFORM._serialized_start=231
  _SIGNUPFORM._serialized_end=310
  _SIGNUPSERVICE._serialized_start=312
  _SIGNUPSERVICE._serialized_end=398
# @@protoc_insertion_point(module_scope)
