# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\x12\x0cmoviePackage\"\x07\n\x05\x45mpty\"E\n\x16UpdateMovieInfoRequest\x12\x11\n\tmovieName\x18\x01 \x01(\t\x12\x18\n\x10newScreeningInfo\x18\x02 \x01(\t\")\n\x17UpdateMovieInfoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"!\n\x0cMovieRequest\x12\x11\n\tmovieName\x18\x01 \x01(\t\"<\n\x11MovieCardResponse\x12\'\n\x06movies\x18\x01 \x03(\x0b\x32\x17.moviePackage.MovieCard\";\n\x08\x42\x36\x34Image\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"C\n\tMovieCard\x12\r\n\x05title\x18\x01 \x01(\t\x12\'\n\x07\x63\x61rdImg\x18\x02 \x01(\x0b\x32\x16.moviePackage.B64Image\"\xbc\x01\n\x07MovieBg\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08subTitle\x18\x03 \x01(\t\x12(\n\x08titleImg\x18\x04 \x01(\x0b\x32\x16.moviePackage.B64Image\x12-\n\rbackgroundImg\x18\x05 \x01(\x0b\x32\x16.moviePackage.B64Image\x12\x0f\n\x07theatre\x18\x06 \x01(\t\x12\x11\n\tmovieType\x18\x07 \x01(\t\"8\n\x0fMovieBgResponse\x12%\n\x06movies\x18\x01 \x03(\x0b\x32\x15.moviePackage.MovieBg2\x85\x03\n\x0cMovieService\x12>\n\x06GetAll\x12\x13.moviePackage.Empty\x1a\x1f.moviePackage.MovieCardResponse\x12\x42\n\nGetPlaying\x12\x13.moviePackage.Empty\x1a\x1f.moviePackage.MovieCardResponse\x12\x41\n\tGetComing\x12\x13.moviePackage.Empty\x1a\x1f.moviePackage.MovieCardResponse\x12\x46\n\tGetAMovie\x12\x1a.moviePackage.MovieRequest\x1a\x1d.moviePackage.MovieBgResponse\x12\x66\n\x17UpdateReservedMovieInfo\x12$.moviePackage.UpdateMovieInfoRequest\x1a%.moviePackage.UpdateMovieInfoResponseb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_UPDATEMOVIEINFOREQUEST = DESCRIPTOR.message_types_by_name['UpdateMovieInfoRequest']
_UPDATEMOVIEINFORESPONSE = DESCRIPTOR.message_types_by_name['UpdateMovieInfoResponse']
_MOVIEREQUEST = DESCRIPTOR.message_types_by_name['MovieRequest']
_MOVIECARDRESPONSE = DESCRIPTOR.message_types_by_name['MovieCardResponse']
_B64IMAGE = DESCRIPTOR.message_types_by_name['B64Image']
_MOVIECARD = DESCRIPTOR.message_types_by_name['MovieCard']
_MOVIEBG = DESCRIPTOR.message_types_by_name['MovieBg']
_MOVIEBGRESPONSE = DESCRIPTOR.message_types_by_name['MovieBgResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.Empty)
  })
_sym_db.RegisterMessage(Empty)

UpdateMovieInfoRequest = _reflection.GeneratedProtocolMessageType('UpdateMovieInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMOVIEINFOREQUEST,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.UpdateMovieInfoRequest)
  })
_sym_db.RegisterMessage(UpdateMovieInfoRequest)

UpdateMovieInfoResponse = _reflection.GeneratedProtocolMessageType('UpdateMovieInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMOVIEINFORESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.UpdateMovieInfoResponse)
  })
_sym_db.RegisterMessage(UpdateMovieInfoResponse)

MovieRequest = _reflection.GeneratedProtocolMessageType('MovieRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEREQUEST,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.MovieRequest)
  })
_sym_db.RegisterMessage(MovieRequest)

MovieCardResponse = _reflection.GeneratedProtocolMessageType('MovieCardResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIECARDRESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.MovieCardResponse)
  })
_sym_db.RegisterMessage(MovieCardResponse)

B64Image = _reflection.GeneratedProtocolMessageType('B64Image', (_message.Message,), {
  'DESCRIPTOR' : _B64IMAGE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.B64Image)
  })
_sym_db.RegisterMessage(B64Image)

MovieCard = _reflection.GeneratedProtocolMessageType('MovieCard', (_message.Message,), {
  'DESCRIPTOR' : _MOVIECARD,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.MovieCard)
  })
_sym_db.RegisterMessage(MovieCard)

MovieBg = _reflection.GeneratedProtocolMessageType('MovieBg', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEBG,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.MovieBg)
  })
_sym_db.RegisterMessage(MovieBg)

MovieBgResponse = _reflection.GeneratedProtocolMessageType('MovieBgResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEBGRESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:moviePackage.MovieBgResponse)
  })
_sym_db.RegisterMessage(MovieBgResponse)

_MOVIESERVICE = DESCRIPTOR.services_by_name['MovieService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=29
  _EMPTY._serialized_end=36
  _UPDATEMOVIEINFOREQUEST._serialized_start=38
  _UPDATEMOVIEINFOREQUEST._serialized_end=107
  _UPDATEMOVIEINFORESPONSE._serialized_start=109
  _UPDATEMOVIEINFORESPONSE._serialized_end=150
  _MOVIEREQUEST._serialized_start=152
  _MOVIEREQUEST._serialized_end=185
  _MOVIECARDRESPONSE._serialized_start=187
  _MOVIECARDRESPONSE._serialized_end=247
  _B64IMAGE._serialized_start=249
  _B64IMAGE._serialized_end=308
  _MOVIECARD._serialized_start=310
  _MOVIECARD._serialized_end=377
  _MOVIEBG._serialized_start=380
  _MOVIEBG._serialized_end=568
  _MOVIEBGRESPONSE._serialized_start=570
  _MOVIEBGRESPONSE._serialized_end=626
  _MOVIESERVICE._serialized_start=629
  _MOVIESERVICE._serialized_end=1018
# @@protoc_insertion_point(module_scope)
